// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-4yLjAiPmfv4GbyzLxxvfB176frkABt8',
    appId: '1:47759382166:web:13e25ec236c4dfa6ea54b7',
    messagingSenderId: '47759382166',
    projectId: 'cooszy-users',
    authDomain: 'cooszy-users.firebaseapp.com',
    storageBucket: 'cooszy-users.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEz-GJ6xiues-gaVb30JLr5O_mYI_vuW0',
    appId: '1:47759382166:android:bfa2e98066466674ea54b7',
    messagingSenderId: '47759382166',
    projectId: 'cooszy-users',
    storageBucket: 'cooszy-users.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVPzbenhzA9QM36pB6DfdfIv0lvicXvg8',
    appId: '1:47759382166:ios:2fbdd3e98e682bdaea54b7',
    messagingSenderId: '47759382166',
    projectId: 'cooszy-users',
    storageBucket: 'cooszy-users.firebasestorage.app',
    iosBundleId: 'com.example.cooszyPre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVPzbenhzA9QM36pB6DfdfIv0lvicXvg8',
    appId: '1:47759382166:ios:2fbdd3e98e682bdaea54b7',
    messagingSenderId: '47759382166',
    projectId: 'cooszy-users',
    storageBucket: 'cooszy-users.firebasestorage.app',
    iosBundleId: 'com.example.cooszyPre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-4yLjAiPmfv4GbyzLxxvfB176frkABt8',
    appId: '1:47759382166:web:7720485369f63232ea54b7',
    messagingSenderId: '47759382166',
    projectId: 'cooszy-users',
    authDomain: 'cooszy-users.firebaseapp.com',
    storageBucket: 'cooszy-users.firebasestorage.app',
  );
}
